#!/usr/bin/env bash
#install ngix and put holberton inside

sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo chmod 777 /var/www/html/index.html
echo 'Holberton School' > /var/www/html/index.html